config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :sales
  end
  namespace :admin do
    resources :customers
  end
  namespace :admin do
    resources :products
  end
  #devise_for :users, class_name: "Admin::User"
  #devise_for :users, ActiveAdmin::Devise.config
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  	devise_for :admin, :controllers => { registrations:  'admin/registrations',
                                        sessions:       'admin/sessions',
                                        passwords:      'admin/passwords',
                                        confirmations:  'admin/confirmations'
  	},
  	class_name: "Admin::User"
  	root 'posts#index'

  	get 'about' => 'pages#about'

  	namespace :admin do
	  controller :admin do
	    get '/', action: :index
	    get :sign_in
	    get :logout
	  end
	  resources :dashboard
    resources :product
  
	end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/customer.rb
class Admin::Customer < ApplicationRecord
end

app/models/admin/product.rb
class Admin::Product < ApplicationRecord
end

app/models/admin/sale.rb
class Admin::Sale < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  before_save :multiplication
  def multiplication
    amount = quantity * 5
  end
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
	before_action :authenticate_admin!
	def index
		redirect_to admin_dashboard_index_path
		
		
	end

	

	
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    @admin_products = Admin::Product.all
    puts @admin_products.inspect
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Admin::Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Admin::Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:admin_product).permit(:productCode, :productName, :productCost)
    end
end

app/controllers/admin/sales_controller.rb
class Admin::SalesController < ApplicationController
  before_action :set_admin_sale, only: %i[ show edit update destroy ]

  # GET /admin/sales or /admin/sales.json
  def index
    @admin_sales = Admin::Sale.all
  end

  # GET /admin/sales/1 or /admin/sales/1.json
  def show
  end

  # GET /admin/sales/new
  def new
    @admin_sale = Admin::Sale.new
    @admin_product = Admin::Product.all
    @admin_customer = Admin::Customer.all
  end

  # GET /admin/sales/1/edit
  def edit
    @admin_product = Admin::Product.all
    @admin_customer = Admin::Customer.all
  end

  # POST /admin/sales or /admin/sales.json
  def create
    @admin_sale = Admin::Sale.new(admin_sale_params)
    #Rails.logger.debug("My admin_sale: #{@admin_sale.inspect}")
    respond_to do |format|
      if @admin_sale.save
        #redirect_to @admin_sale
        format.html { redirect_to @admin_sale, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @admin_sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/sales/1 or /admin/sales/1.json
  def update
    respond_to do |format|
      if @admin_sale.update(admin_sale_params)
        format.html { redirect_to @admin_sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sales/1 or /admin/sales/1.json
  def destroy
    @admin_sale.destroy
    respond_to do |format|
      format.html { redirect_to admin_sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_sale
      @admin_sale = Admin::Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_sale_params
      params.require(:admin_sale).permit(:saleCode, :customer_id, :product_id, :quantity, :amount)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protected
	def authenticate_admin!
		if admin_signed_in?
	      super
	    else
	      redirect_to admin_session_path, :notice => 'You must login' unless admin_signed_in?
	      ## if you want render 404 page
	      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
	    end

		#redirect_to admin_session_path, notice: "You must login" unless admin_signed_in?
	end
	def after_sign_in_path_for(resource)
	  stored_location_for(resource) || admin_dashboard_index_path
	end
	def after_sign_out_path_for(resource)
	    if admin_signed_in?
	       
	       admin_dashboard_index_path
	    else
	       admin_session_path
	    end
    end
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us';
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		
		
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sales_helper.rb
module Admin::SalesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/sales/_form.html.erb
<%= form_with(model: admin_sale) do |form| %>
  <% if admin_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_sale.errors.count, "error") %> prohibited this admin_sale from being saved:</h2>

      <ul>
        <% admin_sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :saleCode %>
      <%= form.text_field :saleCode, { class: "form-control" } %>
    </div>
  </div>

  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :customer_id %>
      
      <%= form.collection_select :customer_id, @admin_customer,:id ,:customerName, { include_blank: 'Select Customer' }, { class: "form-control" } %>
    </div>
  </div>

  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :product_id %>
      <%= form.collection_select :product_id, @admin_product,:id ,:productName, { include_blank: 'Select Product' }, { class: "form-control" } %>
    </div>
  </div>

  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, { class: "form-control" } %>
    </div>
  </div>

  <div class="col-sm-3">
    <div class="form-group">
      <%= form.label :amount %>
      <%= form.text_field :amount, { class: "form-control" } %>
    </div>
  </div>

  <div class="mt10 col-sm-3">
    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', admin_sales_path, class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/admin/sales/edit.html.erb
<div class="pageheader">
     <h2> Edit Sale</h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
          <li><%= link_to "Home", admin_dashboard_index_path %></li>
          <li><%= link_to "Sale", admin_sales_path %></li>
          <li class="active">Edit Sale</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
  	<div class="panel panel-default">
    	<div class="panel-body">
      
      		<div class="row">
        		<div class="col-md-12">
					<%= render 'form', admin_sale: @admin_sale %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/sales/index.html.erb
<p id="notice"><%= notice %></p>
<div class="pageheader">
     <h2> Sales</h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
          <li><%= link_to "Home", admin_dashboard_index_path %></li>
          <li class="active">Sales</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-3 mb10">
          
          <%= link_to "Add Sale", new_admin_sale_path, class:"btn btn-success"%>
          
        </div>
      
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="table-responsive">
            <table class="table table-bordered table-striped" id="searchTable" >
              <thead>
                <tr>
                  <th>Salecode</th>
                  <th>Customer</th>
                  <th>Product</th>
                  <th>Quantity</th>
                  <th>Amount</th>
                  <th colspan="3">Action</th>
                </tr>
              </thead>

              <tbody>
                <% @admin_sales.each do |admin_sale| %>
                  <tr>
                    <td><%= admin_sale.saleCode %></td>
                    <td><%= admin_sale.customer.customerName %></td>
                    <td><%= admin_sale.product.productName %></td>
                    <td><%= admin_sale.quantity %></td>
                    <td><%= admin_sale.amount %></td>
                    <td><%= link_to 'Show', admin_sale, class: 'btn btn-success' %></td>
                    <td><%= link_to 'Edit', edit_admin_sale_path(admin_sale), class: 'btn btn-warning' %></td>
                    <td><%= link_to 'Destroy', admin_sale, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

app/views/admin/sales/new.html.erb
<div class="pageheader">
     <h2> Add Sale</h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
          <li><%= link_to "Home", admin_dashboard_index_path %></li>
          <li><%= link_to "Sale", admin_sales_path %></li>
          <li class="active">Add Sale</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
  	<div class="panel panel-default">
    	<div class="panel-body">
      
      		<div class="row">
        		<div class="col-md-12">

					<%= render 'form', admin_sale: @admin_sale %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/sales/show.html.erb
<p id="notice"><%= notice %></p>
<div class="pageheader">
     <h2> Edit Sale</h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
          <li><%= link_to "Home", admin_dashboard_index_path %></li>
          <li><%= link_to "Sale", admin_sales_path %></li>
          <li class="active">Edit Sale</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="panel panel-default">
      <div class="panel-body">
      
          <div class="row">
            <div class="col-md-12">
              <p>
                <strong>Salecode:</strong>
                <%= @admin_sale.saleCode %>
              </p>

              <p>
                <strong>Customer:</strong>
                <%= @admin_sale.customer.customerName %>
              </p>

              <p>
                <strong>Product:</strong>
                <%= @admin_sale.product.productName %>
              </p>

              <p>
                <strong>Quantity:</strong>
                <%= @admin_sale.quantity %>
              </p>

              <p>
                <strong>Amount:</strong>
                <%= @admin_sale.amount %>
              </p>
              <%= link_to 'Edit', edit_admin_sale_path(@admin_sale), class: 'btn btn-primary' %> 
              <%= link_to 'Back', admin_sales_path, class: 'btn btn-danger' %>
            </div>
        </div>
    </div>
  </div>
</div>